# **Library**

In [ ]:
import pandas as pd
import numpy as np

# **Read Dataset**

In [ ]:
!gdown --id 1uA6fyGPLjX57Np7r0LH1_suJXj3VtNW-

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1uA6fyGPLjX57Np7r0LH1_suJXj3VtNW-
To: /content/dataset_cf.csv
100% 1.67k/1.67k [00:00<00:00, 2.64MB/s]


In [ ]:
#membaca dataset dan disimpan pada variabel df
df = pd.read_csv("./dataset_cf.csv")

In [ ]:
#melakukan set index pada column "Nama"
df.set_index(["Nama"], inplace = True, drop = True)

In [ ]:
#menampilkan 5 data teratas
df.head()

Mangga  Jeruk medan  Pisang  Duku  Sawo  \
Nama                                                                      
Restu Aditya Rachman                 5            2       2     3     4   
Muhammad Rizq Athariq                5            3       4     3     3   
Putu Agus Narestha Adi Pratama       5            3       5     5     2   
Muhamad Febiansyah                   5            2       4     3     4   
Muhammad Haidir Ali                  5            3       4     3     4   

                                Pepaya  Manggis  Apel  Durian  BuahNaga  
Nama                                                                     
Restu Aditya Rachman                 4        5     4       5       NaN  
Muhammad Rizq Athariq                5        5     5       1       2.0  
Putu Agus Narestha Adi Pratama       5        5     5       5       5.0  
Muhamad Febiansyah                   2        2     3       5       2.0  
Muhammad Haidir Ali                  5        3     4       5       4.0

In [ ]:
#mengecek apakah terdapat nilai NaN dari setiap kolomnya
df.isnull().sum()

Mangga         0
Jeruk medan    0
Pisang         0
Duku           0
Sawo           0
Pepaya         0
Manggis        0
Apel           0
Durian         0
BuahNaga       1
dtype: int64

# **Data Exploration**

In [ ]:
#melakukan transpose dataset
df_transposed = df.T
df_transposed

Nama         Restu Aditya Rachman  Muhammad Rizq Athariq  \
Mangga                        5.0                    5.0   
Jeruk medan                   2.0                    3.0   
Pisang                        2.0                    4.0   
Duku                          3.0                    3.0   
Sawo                          4.0                    3.0   
Pepaya                        4.0                    5.0   
Manggis                       5.0                    5.0   
Apel                          4.0                    5.0   
Durian                        5.0                    1.0   
BuahNaga                      NaN                    2.0   

Nama         Putu Agus Narestha Adi Pratama  Muhamad Febiansyah  \
Mangga                                  5.0                 5.0   
Jeruk medan                             3.0                 2.0   
Pisang                                  5.0                 4.0   
Duku                                    5.0                 3.0   
Sawo                                    2.0                 4.0   
Pepaya                                  5.0                 2.0   
Manggis                                 5.0                 2.0   
Apel                                    5.0                 3.0   
Durian                                  5.0                 5.0   
BuahNaga                                5.0                 2.0   

Nama         Muhammad Haidir Ali  Masruri Farid Alviyanto  \
Mangga                       5.0                      4.0   
Jeruk medan                  3.0                      2.0   
Pisang                       4.0                      3.0   
Duku                         3.0                      5.0   
Sawo                         4.0                      5.0   
Pepaya                       5.0                      3.0   
Manggis                      3.0                      4.0   
Apel                         4.0                      2.0   
Durian                       5.0                      1.0   
BuahNaga                     4.0                      3.0   

Nama         Irwan Reza Firmansyah  Muhammad Attalariq  Igga Febrian Virgiani  \
Mangga                         5.0                 3.0                    5.0   
Jeruk medan                    2.0                 2.0                    2.0   
Pisang                         4.0                 4.0                    4.0   
Duku                           2.0                 5.0                    2.0   
Sawo                           4.0                 2.0                    3.0   
Pepaya                         4.0                 5.0                    1.0   
Manggis                        3.0                 2.0                    2.0   
Apel                           4.0                 5.0                    4.0   
Durian                         1.0                 2.0                    3.0   
BuahNaga                       4.0                 3.0                    1.0   

Nama         Manuel Benedict  ...  Dion Pratama Putra / pundung  \
Mangga                   5.0  ...                           4.0   
Jeruk medan              3.0  ...                           1.0   
Pisang                   4.0  ...                           1.0   
Duku                     2.0  ...                           4.0   
Sawo                     1.0  ...                           2.0   
Pepaya                   2.0  ...                           1.0   
Manggis                  3.0  ...                           3.0   
Apel                     4.0  ...                           3.0   
Durian                   1.0  ...                           5.0   
BuahNaga                 3.0  ...                           5.0   

Nama         Rafi Anandita W  Edvan Tazul Arifin  Ahmad Zahri R Adam  \
Mangga                   5.0                 4.0                 5.0   
Jeruk medan              3.0                 1.0                 3.0   
Pisang                   5.0                 1.0                 2.0   
Duku       

In [ ]:
#mengambil salah satu data yaitu pada column "Restu Aditya Rachman"
df_corr = df_transposed.corr(method='pearson', min_periods=1).loc[["Restu Aditya Rachman"],:]
df_corr.drop("Restu Aditya Rachman", axis=1, inplace=True)

In [ ]:
#menyimpan data restu kemudian disimpan pada variabel df_restu
df_restu = df_transposed["Restu Aditya Rachman"]
df_transposed.drop("Restu Aditya Rachman", axis=1, inplace=True)

In [ ]:
#menampilkan dataset yang sudah dibersihkan (tidak terdapat restu aditya rachman)
df_transposed

Nama         Muhammad Rizq Athariq  Putu Agus Narestha Adi Pratama  \
Mangga                         5.0                             5.0   
Jeruk medan                    3.0                             3.0   
Pisang                         4.0                             5.0   
Duku                           3.0                             5.0   
Sawo                           3.0                             2.0   
Pepaya                         5.0                             5.0   
Manggis                        5.0                             5.0   
Apel                           5.0                             5.0   
Durian                         1.0                             5.0   
BuahNaga                       2.0                             5.0   

Nama         Muhamad Febiansyah  Muhammad Haidir Ali  Masruri Farid Alviyanto  \
Mangga                      5.0                  5.0                      4.0   
Jeruk medan                 2.0                  3.0                      2.0   
Pisang                      4.0                  4.0                      3.0   
Duku                        3.0                  3.0                      5.0   
Sawo                        4.0                  4.0                      5.0   
Pepaya                      2.0                  5.0                      3.0   
Manggis                     2.0                  3.0                      4.0   
Apel                        3.0                  4.0                      2.0   
Durian                      5.0                  5.0                      1.0   
BuahNaga                    2.0                  4.0                      3.0   

Nama         Irwan Reza Firmansyah  Muhammad Attalariq  Igga Febrian Virgiani  \
Mangga                         5.0                 3.0                    5.0   
Jeruk medan                    2.0                 2.0                    2.0   
Pisang                         4.0                 4.0                    4.0   
Duku                           2.0                 5.0                    2.0   
Sawo                           4.0                 2.0                    3.0   
Pepaya                         4.0                 5.0                    1.0   
Manggis                        3.0                 2.0                    2.0   
Apel                           4.0                 5.0                    4.0   
Durian                         1.0                 2.0                    3.0   
BuahNaga                       4.0                 3.0                    1.0   

Nama         Manuel Benedict  Setyo Aji  ...  Dion Pratama Putra / pundung  \
Mangga                   5.0        4.0  ...                           4.0   
Jeruk medan              3.0        2.0  ...                           1.0   
Pisang                   4.0        4.0  ...                           1.0   
Duku                     2.0        3.0  ...                           4.0   
Sawo                     1.0        1.0  ...                           2.0   
Pepaya                   2.0        2.0  ...                           1.0   
Manggis                  3.0        3.0  ...                           3.0   
Apel                     4.0        5.0  ...                           3.0   
Durian                   1.0        5.0  ...                           5.0   
BuahNaga                 3.0        3.0  ...                           5.0   

Nama         Rafi Anandita W  Edvan Tazul Arifin  Ahmad Zahri R Adam  \
Mangga                   5.0                 4.0                 5.0   
Jeruk medan              3.0                 1.0                 3.0   
Pisang                   5.0                 1.0                 2.0   
Duku                     3.0                 4.0                 1.0   
Sawo                     2.0                 2.0                 1.0   
Pepaya                   1.0                 1.0                 4.0   
Manggis                  3.0                 3.0                 3.0   
Apel      

In [ ]:
#melihat nilai rata-rata dari masing-masing column
df_transposed.mean()

Nama
Muhammad Rizq Athariq             3.6
Putu Agus Narestha Adi Pratama    4.5
Muhamad Febiansyah                3.2
Muhammad Haidir Ali               4.0
Masruri Farid Alviyanto           3.2
Irwan Reza Firmansyah             3.3
Muhammad Attalariq                3.3
Igga Febrian Virgiani             2.7
Manuel Benedict                   2.8
Setyo Aji                         3.2
Annisa Humairo                    3.6
Ananta Ihza Ramadhan              3.5
ghani kamil                       3.4
ragil bagaskoro                   3.1
Rachmi helfianur                  3.6
Jayana Citra                      3.0
Fikri Ilham                       3.2
Muhammad Kiko A Reiki             2.8
Siti Inayah Putri                 2.7
I GSA Putu Sintha Deviya          3.3
Muhamad Rifqi Supriadi            2.7
Sayid Ghufron                     2.9
Nirmalasari Seqip                 3.0
Nurul khaeriyah                   2.9
Azmi Aulia Rahman                 4.0
Muhammad Condro Agung Putro       4.0
Nuraena

In [ ]:
#melihat korelasi antar variable
sim = df_corr.values[0]
sim

array([ 0.11602387,  0.26580477,  0.31137618,  0.48038446,  0.03314968,
        0.11541088, -0.24514517,  0.14567141, -0.10773645,  0.25691   ,
        0.09805807,  0.26580477,  0.05661385,  0.46045546,  0.19814848,
        0.48536267,  0.33968311, -0.24183351,  0.26519742,  0.17162378,
        0.02311251,  0.1470871 ,  0.06373124,  0.20418849, -0.01820893,
       -0.01820893, -0.01820893,  0.77932527,  0.64715023,  0.64715023,
        0.07657049,  0.64715023,  0.21099893,  0.35347339, -0.21153846,
        0.01981072, -0.34596959, -0.15041421, -0.51672654])

# **Result**

In [ ]:
miu = df_transposed.mean().values
miu

array([3.6, 4.5, 3.2, 4. , 3.2, 3.3, 3.3, 2.7, 2.8, 3.2, 3.6, 3.5, 3.4,
       3.1, 3.6, 3. , 3.2, 2.8, 2.7, 3.3, 2.7, 2.9, 3. , 2.9, 4. , 4. ,
       4. , 3.1, 2.9, 2.9, 3.7, 2.9, 2.6, 3. , 3.7, 3. , 2.7, 2.9, 3.2])

In [ ]:
r_miu = df_transposed.T["BuahNaga"].values - miu
r_miu

array([-1.6,  0.5, -1.2,  0. , -0.2,  0.7, -0.3, -1.7,  0.2, -0.2, -0.6,
        0.5,  0.6,  0.9, -0.6,  0. ,  1.8,  0.2, -0.7,  0.7,  0.3, -0.9,
        1. ,  1.1,  1. ,  1. ,  1. , -0.1,  2.1,  2.1,  1.3,  2.1,  1.4,
       -1. , -0.7, -1. , -1.7,  0.1,  0.8])

In [ ]:
sim_r_miu = r_miu*sim
sim_r_miu

array([-0.18563819,  0.13290238, -0.37365142,  0.        , -0.00662994,
        0.08078762,  0.07354355, -0.24764139, -0.02154729, -0.051382  ,
       -0.05883484,  0.13290238,  0.03396831,  0.41440991, -0.11888909,
        0.        ,  0.6114296 , -0.0483667 , -0.18563819,  0.12013665,
        0.00693375, -0.13237839,  0.06373124,  0.22460734, -0.01820893,
       -0.01820893, -0.01820893, -0.07793253,  1.35901548,  1.35901548,
        0.09954163,  1.35901548,  0.2953985 , -0.35347339,  0.14807692,
       -0.01981072,  0.58814831, -0.01504142, -0.41338123])

In [ ]:
#didapatkan hasil prediksi
prediksi = np.sum(sim_r_miu)/np.sum(sim)+df_restu.mean()
prediksi

4.566058691524082

In [ ]:
sum = 0
for i in sim:
  if i > 0.5:
    sum+=i
sum

2.720775956495754

In [ ]:
#didapatkan hasil prediksi menggunakan threshold
prediksi2 = sum/np.sum(sim)+df_restu.mean()
prediksi2

4.23037770857241